### ISSUE TITLE
release

### ISSUE THREAD

**Issue by OtherwisePitt** [rigvedmaanas/CustomTkinterBuilder#2]
news on release project???

**Comment by rigvedmaanas** [comment]
Hi @OtherwisePitt

It's almost done. First release should happen in 2 - 3 days.

**Comment by rigvedmaanas** [comment]
> news on release project???

It's released. Please check [here](https://github.com/rigvedmaanas/CustomTkinterBuilder/releases/tag/v1.0.0)
