### ISSUE TITLE
TROJAN IN YOUR FILE!!

### ISSUE THREAD

**Issue by OtherwisePitt** [rigvedmaanas/CustomTkinterBuilder#3]
![Screenshot 2024-05-25 123950](https://github.com/rigvedmaanas/CustomTkinterBuilder/assets/131406632/2a91e361-5373-48dc-ba03-07b983ac9502)

**Comment by rigvedmaanas** [comment]
Hi @OtherwisePitt,

This is quite normal as I guess because I didn't sign my code (It's really really expensive to get a certificate). If you still don't believe me you could clone the repo from github and run it from there

**Comment by rigvedmaanas** [comment]
I have packaged this using pyinstaller. 
You could take a look at this issue [https://github.com/pyinstaller/pyinstaller/issues/5492](https://github.com/pyinstaller/pyinstaller/issues/5492) which mentions this problem
