### ISSUE TITLE
Questions about control identification and path addition

### ISSUE THREAD

**Issue by LuLuLuOfficial** [rigvedmaanas/CustomTkinterBuilder#6]
Hello.
The window control itself has a position deviation from the red box that identifies its position. Is this the default setting?
One more little question
open an existing directory and add it to the list instead of verifying it, even if it already exists.
![屏幕截图 2024-07-24 040919](https://github.com/user-attachments/assets/9acdc3f1-eea8-45af-9839-fd8a78781a20)

**Comment by rigvedmaanas** [comment]
Hi,

This issue is not present in my system. Could you try changing the scaling of the UI (OS). It might be set to 110% or something. Could you elaborate more on the second question?

**Comment by rigvedmaanas** [comment]
The default red box when clicked on a widget will be along the outline of that widget.

**Comment by FramilLu** [comment]
hanks for getting back to me!!  I'll give that a try later.

**Comment by rigvedmaanas** [comment]
Hi! Did this solve your issue?

**Comment by LuLuLuOfficial** [comment]
Sorry for not replying to you in time. After I adjusted the ratio to 110%, the first problem did not exist anymore. However, I changed to use pyside and pyqt soon after and failed to continue testing the second problem. I'm terribly sorry.

**Comment by LuLuLuOfficial** [comment]
Hi, I retested the second question (when I create a new project with the same path as the old project, I generate the exact same project icon in the project instead of ignoring the request to create the project). Its does not exist now, maybe I was wrong last time, I am very sorry that such a long incident did not end this issue.

**Comment by chenyulue** [comment]
> Hi,
> 
> This issue is not present in my system. Could you try changing the scaling of the UI (OS). It might be set to 110% or something. Could you elaborate more on the second question?

I meet the same problem. Is there any other way to solve it? My scaling is 150%, and if I change it to 110%, the icons in my desktop are too small. So I don't want to change the scaling.
